---
- hosts: react-js

  vars:
    project_path: /var/www
    repository: https://gitlab.com/LeeroyJenkins92/deploy-blue-green.git
    packages:
      - yarn
      - npm
      - nodejs

  tasks:

    - name: "Install GnuPG and GIT"
      apt:
        pkg:
          - gnupg
          - git

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: "Yarn | GPG"
      apt_key:
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
        state: present

    - name: "Yarn | Ensure Debian sources list file exists"
      file:
        path: /etc/apt/sources.list.d/yarn.list
        owner: root
        mode: 0644
        state: touch

    - name: "Yarn | Ensure Debian package is in sources list"
      lineinfile:
        dest: /etc/apt/sources.list.d/yarn.list
        regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
        line: 'deb http://dl.yarnpkg.com/debian/ stable main'
        state: present

    - name: "Yarn | Update APT cache"
      apt:
        update_cache: yes

    - name: "Install the packages YARN, NPM, NodeJS, Nginx"
      apt: 
        pkg: "{{ item }}"
      loop: "{{ packages }}"
      tags: install_packages

    - name: "Set Release Path"
      set_fact:
        release_path: "{{ project_path }}/releases/{{ lookup('pipe','date +%Y%m%d%H%M%S') }}"

    - name: "Create project path"
      file:
        dest: "{{ project_path }}"
        mode: 0755
        recurse: yes
        state: directory

    - name: "Create Relese folder"
      file:
        dest: "{{ release_path }}"
        mode: 0755
        recurse: yes
        state: directory

    - name: "Clone the repository"
      git:
        repo: "{{ repository }}"
        dest: "{{ release_path }}"
    
    - name: "Add IP address of instance to main site" 
      replace:
        path: "{{ release_path }}/src/App.js"
        regexp: 'Test of Revert'
        replace: '{{ ansible_default_ipv4.address }}'
        backup: yes

    - name: "Ensure NPM Installed"
      npm:
        name: pm2
        global: yes

    - name: "Install packages defined in package.json"
      yarn:
        path: "{{ release_path }}"
        
    - name: "Start ReactJS Application"
      command: "pm2 --name ReactJS start npm -- start"
      args:
        chdir: "{{ release_path }}"
      environment:
        PORT: 80





