---
- hosts: react-js
  become: yes

  vars:
    project_path: /var/www
    repository: https://gitlab.com/LeeroyJenkins92/deploy-blue-green.git

  roles:
    - role: reactapp
    
- hosts: nginx
  become: yes

  vars:
    reactjs_host_ip: 192.168.10.3
    reactjs_host_port: 80
    nginx_vhosts:
    - listen: "80 default_server"
      server_name: _
      state: "present"
      template: "{{ nginx_vhost_template }}"
      filename: main.conf
      extra_parameters: |
        location / {
          proxy_pass proxy_pass http://{{ reactjs_host_ip }}:{{ reactjs_host_port }};
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
  pre_tasks:
  - name: Ensure the default nginx symlink absent
    file:
      path: "/etc/nginx/sites-enabled/default"
      state: absent

  roles:
    - role: nginx
    
