---
- hosts: nginx
  become: yes

  vars:
    nginx_vhosts:
    - listen: "80 default_server"
      server_name: _
      state: "present"
      template: "{{ nginx_vhost_template }}"
      filename: main.conf
      extra_parameters: |
        location / {
          proxy_pass http://192.168.10.3:80;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

  pre_tasks:
  - name: Ensure the default nginx symlink absent
    file:
      path: "/etc/nginx/sites-enabled/default"
      state: absent

  roles:
    - role: nginx