---

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "Install GnuPG and GIT"
  apt:
    pkg:
      - gnupg
      - git

- name: "Yarn | GPG"
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present

- name: "Yarn | Ensure Debian sources list file exists"
  file:
    path: /etc/apt/sources.list.d/yarn.list
    owner: root
    mode: 0644
    state: touch

- name: "Yarn | Ensure Debian package is in sources list"
  lineinfile:
    dest: /etc/apt/sources.list.d/yarn.list
    regexp: 'deb http://dl.yarnpkg.com/debian/ stable main'
    line: 'deb http://dl.yarnpkg.com/debian/ stable main'
    state: present

- name: "Yarn | Update APT cache"
  apt:
    update_cache: yes

- name: "Install the packages YARN, NPM, NodeJS, Nginx"
  apt: 
    pkg: "{{ item }}"
  loop: "{{ packages }}"
  tags: install_packages

- name: Ensure Nginx is not installed
  apt:
    name: nginx
    state: absent

- name: Ensure Nginx is stopped
  ansible.builtin.systemd:
    name: nginx
    state: stopped
  ignore_errors: True

- name: Ensure pm2 installed globaly
  npm:
    name: pm2
    global: yes